### ISSUE TITLE
Possible memory leak in watchtheme

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor#1082]
When running the tutor in dev mode and making changes in the indigo theme, the watchtheme service keeps trying to compile SCSS files, causing a system freeze.

https://github.com/overhangio/tutor/assets/49523567/105747c6-d112-4aaf-b937-e262f82fd2cb

tutor version 17.0.4
OS: Ubuntu 22.04

**Comment by kdmccormick** [comment]
Without having reproduced the bug yet, my first guess would be that the theme compilation is editing a file that watch-sass is watching, creating an infinite loop. That would be a bug -- the generated CSS output *should* be completely ignored by the watch-sass watcher -- but it's possible I have the config wrong. I can dig in today.

@CodeWithEmad could you tell me the version numbers for tutor and tutor-indigo you're using (or commit hashes if nightly), and your edx-platform commit hash if you're bind-mounting it?

**Comment by CodeWithEmad** [comment]
tutor==17.0.4
tutor-indigo==17.4.2

**Comment by regisb** [comment]
Oh my bad, in v17 Tutor did not make use of `npm run watch-sass` yet. @CodeWithEmad can you try to reproduce the issue in v18?

**Comment by kdmccormick** [comment]
Ah right, `npm run watch-sass` was experimental in Quince, which is why Tutor still recommended `openedx-assets watch-themes` in v17. The npm commands only became stable in Redwood / v18. I think this was one of the bugs that I hadn't worked out yet in Quince. I believe [this is the edx-platform commit that fixed it](https://github.com/openedx/edx-platform/pull/34318).

**Comment by CodeWithEmad** [comment]
Thank you so much for the explanation. I'll close this one and will try it on v18.
