### ISSUE TITLE
Tutor branches rename

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/tutor#1096]
This issue is to track the implementation/changes proposed in https://discuss.openedx.org/t/tep-rename-nightly-main-and-master-release/12994. 

- Update branch names in tutor core and plugins
  - ~~nightly --> next~~ nightly --> main
  - master --> release
- Ensure github workflows are updated to represent the new branch naming
- Ensure the GitLab build pipelines are upgraded to ensure releases and sync work as expected

**Comment by kdmccormick** [comment]
The Core PRs for this are ready:
* https://github.com/overhangio/tutor/pull/1153
* https://github.com/overhangio/tutor/pull/1154

If you like those PRs @regisb and @DawoudSheraz , then I can start asking plugin maintainers to make PRs. Once the plugin PRs and the Edly-internal PRs are ready, we can merge all at once, and then Regis can change the branch names in GitHub.

I'm willing to make that happen before Sumac release, but I'm also willing to wait if it seems like too much change during the release testing phase.

**Comment by regisb** [comment]
I'm happy with those PRs, thanks for opening them Kyle. But shouldn't they target the "nightly" branches? It's a major breaking change, after all.

If necessary I can make the `s/nightly/next/g` sed replacements in plugins and push straight to the git repos.

**Comment by regisb** [comment]
I think we should make that change before we release tutor v19.0.0. Otherwise we are going to find ourselves with a big, risky change to merge in a very short time.

**Comment by kdmccormick** [comment]
> If necessary I can make the s/nightly/next/g sed replacements in plugins and push straight to the git repos.

I would not oppose that!

As far as I can tell, those PRs will simply be documentation updates. The timing of them is not so sensitive. 

> But shouldn't they target the "nightly" branches? It's a major breaking change, after all.

Right, uhhh, stepping back... it seems that we have seven things to coordinate:

1. The Sumac release on Dec 09
2. [The big Tutor PR](https://github.com/overhangio/tutor/pull/1153), which affects docs, GH workflows, and the setting of OPENEDX_COMMON_VERSION.
3. [The version-suffix Tutor PR](https://github.com/overhangio/tutor/pull/1154), which just changes tutor_nightly to tutor_next
4. The core branch renaming in `overhangio/tutor` GitHub settings, which only a repo admin (not I) can do.
5. The plugin branch renamings in `overhangio/tutor-*` GitHub settings, which only a repo admin can do.
6. [The TPI PR](https://github.com/overhangio/tpi/pull/6), which adds the `next` index and switches from `@nightly` branches to `@next` branches.
7. The Edly GitLab pipeline updates

No matter how we order these, it seems that there will necessarily be some moments of disruption. Since many of these have to be done by Edly, I can't say what the easiest route forward is, so I leave the decision to you folks. Just let me know what branches my PRs should target and I will do that 😄 Or, feel free to take over those PRs and operate them yourselves if that's easier.

**Comment by DawoudSheraz** [comment]
As per the latest comments https://discuss.openedx.org/t/tep-rename-nightly-next-and-master-release/12994/9?u=syed_muhammad_dawoud, the new names would be:
- master --> release (default)
- nightly --> main

**Comment by regisb** [comment]
For the record, GitHub users will have to run the following git commands:

```
git branch -m master release
git fetch origin
git branch -u origin/release release
git remote set-head origin -a

git branch -m nightly main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

(That is, assuming that the remote name is "origin")

**Comment by regisb** [comment]
All done \o/

**Comment by DawoudSheraz** [comment]
@kdmccormick Thanks for initiating this.

@regisb Thank you for your help in this entire epic, be it the guidance or helping with renaming/merging with your terminal magic 🧙🏽 🪄. You rock, as always.  I learned quite a few neat tricks with this work.

I have created an announcement on discuss https://discuss.openedx.org/t/tutor-branches-rename/14455.
