### ISSUE TITLE
Transcript doesn’t show in LMS

### ISSUE THREAD

**Issue by jevilla94** [overhangio/tutor#229]
**Bug description**
Hi @regisb 

The situation is this:  in the CMS the transcript it's visible, but in the LMS it isn't

Even in the demo course, in the CMS are observed the transcript in the videos without problem, but when you view them in live version in the LMS you can't see the transcript.

**How to reproduce**
If you want reproduce this, you only have to see in the demo course one video in CMS, for example in the unit: “Working with Videos” (you can see here the transcript), then when you click on the ‘view live version’ button, that transcript aren't shown in LMS.

**Environment**
The technical features:
- OS: Ubuntu 16.04
- Tutor version: Tutor 3.4.3

**Additional context**

**Comment by regisb** [comment]
Hi @jevilla94! Thanks for the report. I'm trying to reproduce the issue. In the "working with videos" unit of the demo course, there is a video named "Science and Cooking Chef Profile: JOSÉ ANDRÉS". In the CMS I see no transcript:

![cms_no_transcript](https://user-images.githubusercontent.com/44319/60689032-e18b0b80-9eeb-11e9-9936-a813baa255bc.png)

Can you please share the transcript for that video? Otherwise I won't be able to reproduce the issue.

**Comment by jevilla94** [comment]
Hi @regisb 

I share you the transcript of the video "Science and Cooking Chef Profile: JOSÉ ANDRÉS", I hope this is useful for you.

[Cooking.zip](https://github.com/overhangio/tutor/files/3363511/Cooking.zip)

**Comment by regisb** [comment]
@jevilla94, thanks for the quick response. I managed to reproduce the issue. Here is the partial stacktrace:

```
...
lms_1             |     transcript = get_video_transcript_content(edx_video_id, lang)
lms_1             |   File "/openedx/edx-platform/common/lib/xmodule/xmodule/video_module/transcripts_utils.py", line 575, in get_video_transcript_content
lms_1             |     transcript = edxval_api.get_video_transcript_data(edx_video_id, language_code)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/edxval/api.py", line 292, in get_video_transcript_data
lms_1             |     return dict(file_name=video_transcript.filename, content=video_transcript.transcript.file.read())
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 51, in _get_file
lms_1             |     self._file = self.storage.open(self.name, 'rb')
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 38, in open
lms_1             |     return self._open(name, mode)
lms_1             |   File "/openedx/venv/local/lib/python2.7/site-packages/django/core/files/storage.py", line 300, in _open
lms_1             |     return File(open(self.path(name), mode))
lms_1             | IOError: [Errno 2] No such file or directory: u'/openedx/data/uploads/video-transcripts/1808edc3b0804edf9a63b93fcfdc72f4.sjson'
```

The issue is that static files uploaded in the CMS are not shared with the LMS. This is a tricky issue, as I didn't know that the CMS and the LMS had to share static assets. I'll work on it but it might take some time. Meanwhile, if you are starting a new platform, I suggest you try out the MinIO plugin, which should solve your issue: https://github.com/overhangio/tutor/tree/master/plugins/minio However, do not install this plugin on an already running platform, or you run the risk of losing all your static assets.
