### ISSUE TITLE
how to config smtp use tls?

### ISSUE THREAD

**Issue by carlos-wong** [overhangio/tutor#230]
I think is a config issue

**Comment by regisb** [comment]
I think the issue is how you ask questions. Please take the time to add details to your question, including what you are trying to achieve and what you tried. There is an issue template which you purposefuly deleted, and this is not cool. I do not want to take more time to answer your question than you spent writing it.

**Comment by carlos-wong** [comment]
Ok, sorry.  I will create a new issue use the template

**Comment by regisb** [comment]
@carlos-wong feel free to edit this issue to rephrase your question and I'll rephrase my answer.

**Comment by carlos-wong** [comment]
ok, thanks
