### ISSUE TITLE
Use an a preset SQL file instead of migrating from scratch

### ISSUE THREAD

**Issue by OmarIthawi** [overhangio/tutor#238]
It takes a lot of time to migrate the edxapp mysql database. I think it would make sense to start with a database dump.

**Comment by regisb** [comment]
Hey @OmarIthawi! Yes, I have thought about this for a long time. The thing is that pre-loading sql assets is not for everyone. For instance, I don't want to pre-load sql migrations when running from an edx-platform fork. That's why I think the best solution would be work on a plugin that does just that. It just happens, that I know someone who is currently working on such a plugin. I'll see where that brings him :)

**Comment by OmarIthawi** [comment]
@regisb thanks for the update, that sounds like great news!

**Comment by OmarIthawi** [comment]
Maybe it's not needed :man_shrugging:

**Comment by regisb** [comment]
I think it is! I'm pretty sure it should be possible to achieve this with a plugin. I'll re-open this if you don't mind.

**Comment by regisb** [comment]
I'm quitting on this. If someone comes with a good plugin idea to resolve this I'm all hears. But as far as I am concerned, static asset collection is more time-consuming than migrations.
