### ISSUE TITLE
Error: Command failed with status 1

### ISSUE THREAD

**Issue by TinDang97** [overhangio/tutor#250]
Hi **overhangio**,
I tried to deploy with your command: `"sudo tutor local quickstart"` *docker was installed on root.

But I got  this error:

`Error: Command failed with status 1: docker run --rm -it --volume /home/tindang/.local/share/tutor/data/letsencrypt:/etc/letsencrypt/ -p 80:80 --entrypoint=sh certbot/certbot:latest -e -c certbot certonly --standalone -n --agree-tos -m admin@www.newai.vn/edu/student -d www.newai.vn/edu/student -d www.newai.vn/edu/teacher -d preview.www.newai.vn/edu/student
`

Thank you for help me fix it.

**Comment by TinDang97** [comment]
I find solution is turn off HTTPS access option. Why???

**Comment by regisb** [comment]
Hi @TinDang97!

Please note the following:

1. HTTPS is not supported for local development. This is because of the way SSL validation works. See the [docs](https://docs.tutor.overhang.io/configuration.html#ssl-tls-certificates-for-https-access).
2. You should really not use `sudo` for running docker. Instead, you should add your user to the `docker` group in order to be able to run docker commands. See the [official docker docs](https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user).
