### ISSUE TITLE
raccoongang/edx_xblock_scorm not working with tutor

### ISSUE THREAD

**Issue by vmarc29** [overhangio/tutor#265]
**Is your feature request related to a problem? Please describe.**
When installing the xblock_scorm package, i found out that it was not working properly. The static was properly added and i could upload the file, but somehow when i was trying to open the SCORM package i was getting a 404. 

**Describe the solution you'd like**
I investigated and discovered the "unzip" package is missing and is needed in the CMS container. I just did an "apt-get update && apt-get install unzip" and it was working fine.

**Comment by regisb** [comment]
Hi @vmarc29! Thanks for investigating this issue.
I am reluctant to add `unzip` to the list of installed packages in the openedx docker image, as it is not required by most Open edX installations, and will only contribute to making it heavier. Moreover, I see that `unzip` is required because the xblock makes a call to `os.system('unzip {} -d {}'.format(temporary_path, path_to_file))`. This is a bad practice, and this piece of code could be improved quite simply by using the [zipfile](https://docs.python.org/3.6/library/zipfile.html) standard library. May I suggest you open a pull request or an issue directly in the [xblock repo](https://github.com/raccoongang/edx_xblock_scorm/)?

**Comment by vmarc29** [comment]
ya sure. Just wanted to inform you about it, will check with them.
Regards
Vincent

**Comment by regisb** [comment]
Thanks for the feedback @vmarc29! Please let if and how you manage to get the xblock working.

**Comment by regisb** [comment]
Solved by releasing a fork of the original xblock: https://github.com/overhangio/openedx-scorm-xblock
