### ISSUE TITLE
Extended Courseware Student Module History

### ISSUE THREAD

**Issue by jtopjian** [overhangio/tutor#288]
We're in the process of migrating from one edX environment to a new one based on Tutor. While doing this migration, I copied various settings in order to get feature parity between environments and then investigate any errors that occurred.

One transferred setting was:

```
"ENABLE_CSMH_EXTENDED": true,
```

It appears this setting tells edX to use a separate database for the courseware history, instead of having the history within the main openedx database:

https://edx.readthedocs.io/projects/open-edx-release-notes/en/latest/CSMHE/migration_procedures.html

Having this data in the main openedx database is problematic for large environments and it's recommended to move to the new method of having a separate database for this data. I realize that some environments might not see the scaling issue described, so not having this feature enabled is probably acceptable for most people. However, my concern is that future releases of openedx will require this to be enabled.

From what I've pieced together, the following needs to be done:

1. A new setting in `config.yml` to set `ENABLE_CSMH_EXTENDED` in `cms.env.json` and `lms.env.json`.
2. A new database created in mysql
3. A new database entry in `cms.auth.json` and `lms.auth.json`:

```json
        "student_module_history": {
            "CONN_MAX_AGE": 0,
            "ENGINE": "django.db.backends.mysql",
            "HOST": "localhost",
            "NAME": "edxapp_csmh",
            "OPTIONS": {},
            "PASSWORD": "password",
            "PORT": "3306",
            "USER": "user"
        }
```

4. The following migrations to be run:

```
./manage.py lms migrate --database student_module_history
./manage.py cms migrate --database student_module_history
```

It's very possible there are more steps needed - those are just the ones I identified while investigating.

**Comment by regisb** [comment]
Hi @jtopjian! Thank you the detailed report. I must admit I was not aware of that extended CSMH feature.

I would like to dig the performance issue a little more. As far as I understand, platform managers will encounter latencies only when *all* the following conditions are met:

1. Course staff edits many problem units concurrently.
2. The courseware history data resides in a database that uses the same storage solution as the primary database.

Unless I'm mistaken, simply moving the courseware history database to a separate MySQL instance will not in itself resolve performance issues. This will happen only if that second MySQL database runs on a separate disk. With the changes that you propose, the courseware history database will still be using the same storage solution for most users. Basically, users would need to run the databases on different Kubernetes pods in order to improve performances. Or they could rely on separate RDS databases -- but then I seriously doubt that they would encounter performance issues with a single RDS database. They would probably need to reach edX.org-scale to face these problems.

It looks like @jibsheet created the initial implementation of that feature, back in early 2016 (reference: https://github.com/edx/edx-platform/commit/6f9a3911e5662fd459e397a2fa6e2e834f55446a). Unfortunately, they seem to no longer contribute to Open edX.

@jtopjian Did you face performance issues yourself? Are you running databases on separate disks? Would you be willing to try running Open edX without separating both databases?

**Comment by jtopjian** [comment]
> I must admit I was not aware of that extended CSMH feature.

Yeah, neither was I. I discovered it by copying settings/features that were enabled in another environment of ours that was built by a third party. 

> Would you be willing to try running Open edX without separating both databases?

Yes, that's not an issue for us. The main reason that I opened this issue was in the event that a future release of openedx requires this to be enabled.

**Comment by jibsheet** [comment]
Hi - I wrote this as a member of edX's operational staff.  I don't know their plans for this feature, I know that when the migration ran, multiple edX managed production sites used a single database server with two databases, only one instance used separate database servers (for many reasons).  

My preference is that this feature either be removed, or stop storing history in MySQL.  A plan for changing this feature was left with other members of edX staff when I left.  

You should reach out to the open source team at edX for further information.

I'm going to remove myself from notifications on this issue.

**Comment by regisb** [comment]
That's great, thanks for the explanations @jibsheet :) Since you don't really need this feature @jtopjian I'm going to close this issue. Anyone is free to re-open it if they feel like this feature is actually required.
