### ISSUE TITLE
Error: Command failed with status 1: After running tutor local quickstart with version 3.11.5

### ISSUE THREAD

**Issue by prajaksjit** [overhangio/tutor#300]
**Bug description**
I wanted to install the Tutor with the lastest version v3.11.5 and I got this message:

```
> Error: Command failed with status 1: docker-compose -f /root/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local exec lms sh -e -c dockerize -wait tcp://mysql:3306 -timeout 20s
> 
> export DJANGO_SETTINGS_MODULE=$SERVICE_VARIANT.envs.$SETTINGS
> echo "Loading settings $DJANGO_SETTINGS_MODULE"
> 
> ./manage.py lms migrate
> 
> ./manage.py lms create_oauth2_client \
>     "http://androidapp.com" "http://androidapp.com/redirect" public \
>     --client_id android --client_secret J9Rb1KMUQh3aW1vPPoGmiHKj \
>     --trusted
> 
> # Fix incorrect uploaded file path
> if [ -d /openedx/data/uploads/ ]; then
>   if [ -n "$(ls -A /openedx/data/uploads/)" ]; then
>     echo "Migrating LMS uploaded files to shared directory"
>     mv /openedx/data/uploads/* /openedx/media/
>     rm -rf /openedx/data/uploads/
>   fi
> fi
```

And the LMS website shows "Internal Server Error"

**How to reproduce**
Just follow the installation instruction on https://docs.tutor.overhang.io/install.html

**Environment**
OS: Ubuntu 18.04.4 LTS
Docker version 19.03.6, build 369ce74a3c
docker-compose version 1.25.4, build 8d51620a

**Additional context**
And configuring SMTP to use Gmail seems not to work.
Thank you!

**Comment by demianlicht** [comment]
Did you solve this any way? I'm running into the same issue.

`ERROR: for tutor_local_cms-worker_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for tutor_local_lms_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for cms-worker  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for lms  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
Error: Command failed with status 1: docker-compose -f /home/ubuntu/.local/share/tutor/env/local/docker-compose.yml --project-name tutor_local up --remove-orphans -d`

**Comment by regisb** [comment]
@demianlicht this is a different issue. Please don't comment on other people's unrelated issues. Instead, check the error message on the discussion forums: https://discuss.overhang.io/search?q=COMPOSE_HTTP_TIMEOUT

For instance: https://discuss.overhang.io/t/error-unixhttpconnectionpool/176/2
