### ISSUE TITLE
Studio SIGN UP Triggers LMS Activation Email

### ISSUE THREAD

**Issue by jimttutor** [overhangio/tutor#314]
Hi Regis, I like your docker-based approach to providing an Open edX environment, and plan to deploy it on AWS. In the meantime, I'm testing on a VirtualBox Linux VM (Ubuntu 18.04, assigned 8 GB of RAM) on a Windows 10 host with 32 GB of RAM.

In my test environment, I've tried using the SIGN UP option at the upper right of the Studio home page in both Tutor v3.11.8 and v3.11.9., and am seeing the following oddity: Selecting the SIGN UP option (with URL http://site.com/register?next=http://studio.site.com/) takes me to an LMS sign-up page, and triggers an LMS activation email, with log entry:
       lms-worker_1      | 2020-04-07 18:32:12,304 INFO 113 [edx.celery.task] tasks.py:26 - Activation Email has been sent to User xxx@xxx.xxx

The link within the lms activation email works to provide access to both an LMS account and a CMS account, which I'm guessing is expected; i.e., LMS & CMS don't have separate user databases? (And, in that event, it isn't clear to me why there are separate sign-up pages for LMS & CMS.)

I've found that I can get to the Studio sign-up page by, on the Studio home page, selecting SIGN IN, and then selecting the link for "Don't have a Studio Account? Sign up!" (with URL http://studio.site.com/signup). The "SIGN UP AND START MAKING YOUR <platform name> COURSE" button at the bottom of the Studio home page (with URL http://studio.site.com/signup) also works to get to the Studio sign-up page. 

In my test environment, I'm distinguishing between the LMS & CMS landing pages by using /etc/hosts entries that point to the same local Ubuntu IP Address; e.g.,
       site.com              10.0.0.60
       studio.site.com   10.0.0.60

Perhaps the above oddity (Studio SIGN UP option leads to LMS sign-up page) is nothing more than a quirk that can be ignored. But I'd like to ensure that I'm not seeing unexpected results in my test environment; so, your comments on this will be much appreciated!

--Jim

**Comment by regisb** [comment]
Hi @jimttutor! You are asking different questions here.

> The link within the lms activation email works to provide access to both an LMS account and a CMS account, which I'm guessing is expected; i.e., LMS & CMS don't have separate user databases?

Yes, the LMS and CMS share the same database.

> (And, in that event, it isn't clear to me why there are separate sign-up pages for LMS & CMS.)

In Ironwood, the signup page is the same for the LMS and the CMS when https is activated. They used to be separate, because the CMS and the LMS run on different domain names.

> Perhaps the above oddity (Studio SIGN UP option leads to LMS sign-up page) is nothing more than a quirk that can be ignored.

No, this is not a quirk, this is correct.

Note that any user created from the LMS or the CMS signup page will not immediately be able to create courses. This is normal behaviour: otherwise, anyone could start creating courses on your platform, which would be a mess.

I'm closing this now, as this is not really an issue. For other questions and comments, please go to the official forums: https://discuss.overhang.io

**Comment by jimttutor** [comment]
Thanks for the response, Regis.
