### ISSUE TITLE
Are you open to PR on the Kubernetes part ?

### ISSUE THREAD

**Issue by menardorama** [overhangio/tutor#335]
I've got several modifications on the K8s part in order to be compliant on our Kubernetes infrastructure and I wonder if you would agree to accept such modifications.

1. Remove mysql job : use a configmap to define mysql configuration (for character-set-server=utf8 and collation-server=utf8_general_ci); update the auth.env mysql secret to have openedx related variables (DB, USER and PASSWORD) ; update mysql deploy to use the secret as env variables and be able to initialise directly the DB at first start.

2. Tutor is not compatible with kubernetes bellow 1.14 : root cause is apiversion on the ingress. Using kustomize for that would fix the issue.

3. Ability to define storage size and eventually a storage class for persistent volumes.

4. TBD : Implement imagePullSecret option in the deployements (usefull for private docker regsitry.

5. TBD : Rebuild images to run as nonroot and add Security contexts

If you agree I can backport my modifications in a PR.

Thanks

**Comment by regisb** [comment]
Hi @menardorama! Thanks for your suggestions. 

> Remove mysql job : use a configmap to define mysql configuration (for character-set-server=utf8 and collation-server=utf8_general_ci); update the auth.env mysql secret to have openedx related variables (DB, USER and PASSWORD) ; update mysql deploy to use the secret as env variables and be able to initialise directly the DB at first start.

The mysql-job is necessary, as more than one database is needed to run Open edX. For instance, the Discovery and Ecommerce application plugins require the creation of separate databases.

However, it is quite possible to replace the `auth.env` mounted file by a single environment variable. I forget the initial rationale behind using a setting file instead of env variables, but today it makes more sense to define the root user password with env vars.

> Tutor is not compatible with kubernetes bellow 1.14 : root cause is apiversion on the ingress. Using kustomize for that would fix the issue.

Yes, but as mentioned in the docs the Ingress part of the K8s deployment is very much up to the user. The example Ingress is provided as a baseline to resolve most use cases, but it cannot possibly address all of them.

> Ability to define storage size and eventually a storage class for persistent volumes.
> TBD : Implement imagePullSecret option in the deployements (usefull for private docker regsitry.

Could we obtain the same result by allowing users to implement custom patches? https://kubectl.docs.kubernetes.io/pages/app_management/field_merge_semantics.html
For instance, we could have a `tutor/env/k8s/patches` folder (initially empty) that would be automatically imported in the `kustomization.yml` file and where users could add as much customization as they want to their platform. I am in favour of this more generic approach vs adding many K8s-specific Tutor settings.

> TBD : Rebuild images to run as nonroot and add Security contexts

This would be great, but it's not so easy... Remember that this needs to also work for local deployments, with docker-compose, and with local development, with the openedx-dev image.

(next time, can you please create new conversations on https://discuss.overhang.io? The forums are more conducive to discussion, and I like to keep only actual conversations that revolve around actual issues in Github)
