### ISSUE TITLE
unRAID support?

### ISSUE THREAD

**Issue by argash** [overhangio/tutor#440]
Any chance for an unRAID CA template?

**Comment by regisb** [comment]
You're kidding, right? You dismissed the GitHub issue templates, didn't bother looking at the docs, dismissed all the warning signs, ignored previous GitHub issues, zipped by the forums to post here a 7-word question?

**Comment by argash** [comment]
1) Not kidding.
2) I was not presented with a template, not sure why.
3) I did search the documentation and saw no results for unRAID.
4) What warning signs? That the team has condescending assholes on it? Kind of wish I hadn't missed those warning signs now.
5) I did search closed and opened issues, saw no mention of unRAID.
6) I must have missed that there is forum based support.

In all honesty. my 7 word question was, concise, polite, and really only required a "Yes, No, or Maybe in the future" type response. Meanwhile your 34 word response was rude, condescending, and failed to actually answer my question.

I mean I get that this is a "free" program but perhaps some professionalism might be in order? For now I guess I will move my search elsewhere to other projects.

**Comment by regisb** [comment]
I'll post here a few reminders for the sake of others who might contribute to this project -- or just any other open source project, for that matter:

1. Direct insults are not tolerated.
2. Users are not customers. Users and developers are collaborators whose common goal is to improve the software that they are building.
3. Different software projects have different rules. When first contributing to a project, it is common courtesy to inquire about the rules of a project. Such rules are usually outlined in the project README or CONTRIBUTING documents.

Item 2 stems from the fact that users do not pay the developers anything. In order to contribute positively and add value to a project, users need to provide some amount of work. Otherwise, they are actually detrimental to the whole project.

As a corollary of item 2, contributors are expected to go the extra mile to thoroughly describe the issue they are facing, such that developers can understand the context in which the issue is happening, its importance and relevance. As a rule of thumb, users should not expect to get answers that contain more words than the questions they ask.

One more word about GitHub issues: GitHub makes it very easy for users to add items to the developers' TODO list. It's great for developers to be able to collect feedback in such an efficient way. The obvious downside is that poorly written GitHub issues add to the developers load, may decrease their morale and, in the worst cases, are contributing factors that lead to burn out and depression -- I'm speaking from experience here. This is why many FLOSS projects stop using GitHub issues. And this is why we added issue templates to this repo. @argash if for some reason you were not presented with an issue template, then this is a GitHub issue that should probably be reported. Please describe the steps you followed, if possible with screenshots. That is, if you did not simply ctrl+a-del the whole thing.

Finally, a note to other @overhangio/tutor-developers: my own reply to the initial issue here should not be taken as a template for good response. In a perfect world I would have had the patience and the kindness to ask @argash to reformulate its query and post it in the forums. I did not and got angry -- but you know what? It's okay to be angry sometimes. First, I'm only human, not Buddha. Second, anger conveys the information that some things are really, really not okay -- just like adults would do with children.

I hope that this kind of situations does not arise too often. If people have ideas to improve the GitHub issue workflow and template, I'm all ears.
