### ISSUE TITLE
the latest mfe plugin is not on tutors latest release.

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor#458]
Hi
in [tutor-mfe](https://github.com/overhangio/tutor-mfe) repository, some typo changed (6 days ago) and got a new version 12.0.1.
but I think you forget to update the binary release package.
the current version of the mfe plugin on tutor's latest release is 12.0.0.

please update the release version

**Comment by regisb** [comment]
Hi @CodeWithEmad! Yes, I'm aware of that. New binary releases are produced when an actual Tutor release is created. You will have to wait until we release tutor==12.0.1 to get a new binary -- which is why we should actually recommend that people install from pip, and not from the binary.

I'm closing this since this is not an actual issue with Tutor.
