### ISSUE TITLE
Plugin hooks are not supported by the yaml plugin API

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#499]
**Is your feature request related to a problem? Please describe.**

YAML-formatted Tutor plugins may not implement initialization hooks. The reason for that is that init hooks are actually templates with a specific path that are loaded at runtime. This is counter-intuitive and not very easy to grasp.

Note that the same problem applies to templates. It would make sense to be able to write custom templates in YAML plugins, too.

**Describe the solution you'd like**

Hooks should be declared as raw strings, just like patches. Thus, a plugin should be able to declare hooks as follows:

```
hooks = {
    "init": [
        {
            "service": "lms",
            "command": "..."
        }
    ]
}
```

**Describe alternatives you've considered**

It is still possible to implement hooks (and templates) with the Python API, but this is inconvenient. YAML plugins are more easily shared on the forums.

**Additional context**
See initial conversation: https://discuss.overhang.io/t/how-to-use-learning-mfe-on-tutor/1863/3

**Comment by ghassanmas** [comment]
So if I get your solution right: Once implemented , will end up with two types of init hooks: a string (which refer to the directory where the hook is) or dict which means it's command to run. 

So let me know what you think of this flow to implement the solution: 
When looping over hooks of a plugin https://github.com/overhangio/tutor/blob/f2260006bd370584434b935f90e85e3dcee776c2/tutor/plugins.py#L131 
- We first check if the init hook is a string or object 
- If string just move forward with how it is, in order to not break already written plugins
- If dict then create a file hooks/<service-name>/init file 
- Write the command value in that file. 
- Make sure that file/diectory is then would be included or added to `template_root` ref: https://github.com/overhangio/tutor/blob/f2260006bd370584434b935f90e85e3dcee776c2/tutor/plugins.py#L59 

Is that a possible to implment the solution? if yes then I would move forward with creating a proof of concept.

**Comment by regisb** [comment]
Thanks for your interest in this matter @ghassanmas! I think we should not stick with the "hooks as files" approach. Currently, we iterate over hook template files with `iter_plugin_hooks`, which itself yields from `iter_hooks`. This method yields a `(hook name, hook file path)` such that job runners run `run_job_from_template` using the hook path. This approach is uselessly complex, in my opinion. So we should refactor the code such that `iter_hooks` actually yields the unrendered content of the hook files.

Once this refactor is done, we should allow the definition of hooks as follows:

```
hooks = {
    "init": [
        {
            "name: "forum",
            "shell": "./manage.py ..."
        }, ...
    ]
}
```

Does that make sense?

**Comment by ghassanmas** [comment]
So if I understand correctly, the apporach is going to change how the plugins hooks (as data type)  from  (dicts and lists(of file path) ) to just  dicts like structure: 
And it's the concern of plugins.py module to handle the case when command of hook is in a file (instead of making jobs.py handle this by renedering a template file).  And I assume we want to keep it possible for hooks command to be in files since sometimes it might be such a complicated command(s)  to have it just as a string in dict, right?. 

Are we synced so far?

**Comment by regisb** [comment]
I think we are in agreement, yes. But just to be clear: the previous syntax and type should remain supported, for backward compatibility with existing plugins.
