### ISSUE TITLE
Upgrading from one release to the next bypasses image building

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor#545]
**Bug description**

When upgrading from one release to the next, the upgrade process does not even attempt to rebuild images. Yet, this might be required in some environments, for instance when Docker images have been customized. To rebuild an image, one has to first run `tutor config save` to update the environment, but this will override the tutor "version" file. Thus, running "quickstart" will bypass the upgrade process.

There are different possible solutions:

1. Improve the docs on upgrading to a new major release. 
2. After the upgrade process is over, ask whether we should re-build images; if yes, which ones?
3. After the upgrade process is over, print in the standard output how to re-build images.

**Additional context**

This issue was first raised here: https://discuss.overhang.io/t/upgrade-logic-issue-with-custom-images/2212

**Comment by GeoffreyFrogeye** [comment]
> 1. Improve the docs on upgrading to a new major release.

This is the easiest from a development point of view, but maybe some user will miss it.

> 2. After the upgrade process is over, ask whether we should re-build images; if yes, which ones?

Some images are customised with some arguments (e.g. with forks). If we don't deal with it (which would be complicated), we're at risk of creating some confusion.

> 3. After the upgrade process is over, print in the standard output how to re-build images.

I suppose it is the nicest. Would work well with 1.

Although all of those have an issue: before the images are built, Tutor will be started with the tutor-provided version of the images, which is not ideal. We can stop them until they are built, but this is not ideal either, because we still have to wait for them to be built. I already find it annoying that the (non-openedx) images are pulled after Tutor is stopped, it would be great if we could keep upgrade downtime to a minimum.

Ideally the upgrade command (and thus quickstart) would work as intended regardless of whether `tutor config save` was run beforehand (not sure if it's the case for everyone, but this is the command I'm quite trigger-happy with, considering I wasted some rebuilding and downtime because I forgot to run it...).

Issue with that would be: how do we know which version to upgrade from then, if we don't have the old `env/version`? Two possible solutions:

- Make a file called `env/last_upgarde` which stores the last version Tutor upgraded to (which should also be set on first install. How to detect a first install though would be open for discussion), which is not overriden on `tutor config save`.
- Detect which version of Open edX is running in the exsiting `cms`/`lms` container. We probably shouldn't use the image name as it may vary among forks. But there is most certainly some python code that can be executed into the container to get the running release. If there is no container, or that exec fail, we can just ignore to upgrade (maybe add a warning for the latter case).

I personally would go with the later solution, which sounds more robust as it doesn't rely on Tutor-written data. But also more complex as well.

What do you think? I'm not super familiar with tutor, so maybe there's a big thing I am missing...
