### ISSUE TITLE
ARM MariaDB permission error

### ISSUE THREAD

**Issue by yarons** [overhangio/tutor#590]
**Bug description**
I followed the ARM guide on starting tutor with MariaDB.
Apparently there's a permission problem:

```
2022-02-18 05:50:33+00:00 [Note] [Entrypoint]: Initializing database files
2022-02-18  5:50:33 0 [Warning] Can't create test file /var/lib/mysql/ffffffff.lower-test
2022-02-18  5:50:33 0 [ERROR] mysqld: Can't create/write to file '/var/lib/mysql/aria_log_control' (Errcode: 13 "Permission denied")
2022-02-18  5:50:33 0 [ERROR] mysqld: Got error 'Can't create file' when trying to use aria control file '/var/lib/mysql/aria_log_control'
```

**How to reproduce**
Just follow the tutor for ARM guide.

**Environment**
Ubuntu 20.04 on ARM64 AWS instance

**Additional context**
I managed to solve it, the owner of `$HOME/local/share/tutor/data` was root:root (0:0) while the app inside the container is running as 999:999 so I chowned the data dir and it started correctly.

**Comment by yarons** [comment]
The proper solution would be building the permissions docker instead of assuming it's the right architecture.

So I'm guess that fixing the openedx-permissions docker is the right way to go, in order to do that there should be an extra step in the ARM guide telling the user to run "tutor images build permissions" in order to fix all the chaos with UID 1000 and UID 999 which I had to figure myself by throughly reading the Dockerfiles and docker-compose.yml.

**Comment by regisb** [comment]
What is the command that is triggering the error?

Correct me if I'm wrong: the error comes from the fact that the mysql-permissions container is crashing during `tutor local start`. Is that correct? @bradenmacdonald do you confirm?

**Comment by yarons** [comment]
Yes, it's based of the general permission docker.

So if I have to summarize I think that running `docker images build` doesn't build the permission docker so when I'm trying to run `docker local init` I'm seeing that all those dockers are unable to run as they are failing immediately with `Exec format`.

Triggering a `docker build` for the permissions docker as part of the `docker images build` command will probably solve this.

When I come to think about it, if I would just run `docker images build` and then `docker images build permissions` I wouldn't run into this error.

I told you it's an easy one :)
Thanks.

**Comment by bradenmacdonald** [comment]
@yarons @regisb Interesting, I did not run into this myself at all. I'll try to take a look this week and see if I can reproduce. If it's as simple as telling people to run an extra command, that's an easy fix :)

**Comment by yarons** [comment]
@bradenmacdonald Sure, just don't forget #591 which is changing the hard coded architecture name in the Dockerfile, it's a simple step but it can be automated with build-args in the future.

**Comment by bradenmacdonald** [comment]
@yarons @regisb 

I investigated this today and I was able to reproduce the issue on AWS ARM64 instances.

The reason that I didn't encounter this issue when creating [the tutorial](https://docs.tutor.overhang.io/tutorials/arm64.html) is simple: I tested it on a Mac, and Docker for Mac is automatically configured out of the box to be able to run either arm64 or amd64 images (the latter run slowly using qemu, but they do run fine).

So for mysql-permissions, when I tested this on a Mac, the image ran fine. When I tested it on Ubuntu, qemu is not installed not has `binfmt_misc` been configured so that amd64 binaries can be run using it. As a result, the permissions fail.

As @yarons suggested, I think we just need to change the tutorial from saying `tutor images build openedx` to `tutor images build permissions openedx` . There is no harm in rebuilding the permissions containers on Macs, even though it's not strictly needed, and then the instructions should work for both Mac and Linux.

I wasn't able to confirm this was the _only_ fix needed as for some reason I had to manually run `tutor local dc up mysql-permissions` before `tutor local init` would work. But I assume this is just because I hit the error in the first place, and that if I started with rebuilding the permissions before trying `tutor local init` it would have worked.

**Comment by yarons** [comment]
I'm guessing that using my ghcr.io MySQL docker is not a good option, do you want to move it somewhere? Do you think we should even use it?

Thanks!

BTW can we build the permissions docker for more applications? This way we won't need the addition of building the permissions docker for arm64, it will be as smooth as the former process.
