### ISSUE TITLE
arm64: `dockerize: Exec format error` on mysql init

### ISSUE THREAD

**Issue by yarons** [overhangio/tutor#591]
**Bug description**

As part of `tutor local init` which suggests that the `dockerize` command is built for a foreign architecture and thus fails to run:

`docker-compose -f /home/ubuntu/.local/share/tutor/env/local/docker-compose.yml -f /home/ubuntu/.local/share/tutor/env/local/docker-compose.prod.yml --project-name tutor_local -f /home/ubuntu/.local/share/tutor/env/local/docker-compose.jobs.yml run --rm lms-job sh -e -c dockerize -wait tcp://mysql:3306 -timeout 20s`

**How to reproduce**
After fixing the former permission error #590 I ran into this problem.

**Environment**
Ubuntu 20.04 on ARM64 AWS instance

**Additional context**
I found the source:
https://github.com/overhangio/tutor/blob/156ef063ce9b536bb39d239587cd9536970d0004/tutor/templates/build/openedx/Dockerfile#L26
jwilder posted an armhf/aarch64 version but it's called armhf which is inconsistent with the kernel convention so we can try and add a --build-arg to docker to manually switch aarch64 to armhf and keep amd64 intact (uname -m/i/p).
This can be done as part of docker-compose.yml (build arguments).

Since I can live without amd64 I managed to get it working by manually changing amd64 to armhf in the respective openedx Dockerfile instruction.

**Comment by regisb** [comment]
I'm not 100% sure that I understand the issue you are facing. Generally speaking, and to create less confusion, you should post the following information:

1. The exact command you run
2. The full error log

If I interpret your description correctly, you are getting an `Exec format` error when running some command -- I assume `tutor local start`. Can you please confirm? In any case, include the full error log.

If my interpretation is correct, I'm guessing that we should be doing the following:

1. Make it possible to build and run the "permissions" image on arm64
2. Add the instructions to run build the image to the [arm64 tutorial](https://docs.tutor.overhang.io/tutorials/arm64.html).

Right?

**Comment by yarons** [comment]
The command:
`tutor images build`

The error is gone now because it's fixed but the important part was the `Exec format error`.

I'll explain:
`tutor images build` is building this Dockerfile I've mentioned in the "Additional context", the command in this Dockerfile is downloading and installing the amd64 version of Dockerize since it's hard coded.

Later on when I'm trying to run `tutor local init` it will fail because the exectuable is unsuitable for my architecure (I can't remember which feature is calling the dockerize exactly but there is such command).

You interpertation is correct with a small exception:
You should also fix the hard coded amd64 in the dockerize line mentioned (in bold).

```Markdown
 RUN curl -L -o /tmp/dockerize.tar.gz https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-**amd64**-$DOCKERIZE_VERSION.tar.gz \ 
```

After fixing all that we will be able to produce a fully working system on arm64 that we can also push from to the docker registry.

**Comment by bradenmacdonald** [comment]
I reproduced this issue. On Ubuntu arm64, `tutor local init` fails:

```
Starting tutor_local_mysql_1 ... done
sh: 1: dockerize: Exec format error
Error: Command failed with status 2: docker-compose -f /home/ubuntu/.local/share/tutor/env/local/docker-compose.yml -f /home/ubuntu/.local/share/tutor/env/local/docker-compose.prod.yml --project-name tutor_local -f /home/ubuntu/.local/share/tutor/env/local/docker-compose.jobs.yml run --rm lms-job sh -e -c dockerize -wait tcp://mysql:3306 -timeout 20s
```

> jwilder posted an armhf/aarch64 version but it's called armhf which is inconsistent with the kernel convention so we can try and add a --build-arg to docker to manually switch aarch64 to armhf and keep amd64 intact (uname -m/i/p).

It's not an ARMv8/aarch64 version, which is why it doesn't follow the naming convention. There is [an open request to publish an aarch64 build](https://github.com/jwilder/dockerize/issues/143) of dockerize, and a [known issue with the Makefile to build it yourself](https://github.com/jwilder/dockerize/pull/155)

I think this should work: `dpkg --print-architecture |sed s/arm64/armhf/`
and if we replace the hard-coded `amd64` in that `RUN` command with the result of the above shell expression, it should do the right thing. I'm out of time for today, maybe @yarons you can test that?

**Comment by yarons** [comment]
I'll try and see what I can do, I've sent you a mail about it.

Anyways it seems like the right approach because although we can probably build it ourselves (I have a working version of Pritunl-Zero, written in go, in one of my repos) it's pointless because using it for such a small task doesn't really require it to support all the arm64 capabilities, it's not optimized but it works, later on we can try and produce some binaries of our own and propose them to the original project (no new version for 4 years?), which by the way has many successful forks.

Are you sure you want to use the dpkg approach? Wouldn't `uname` or `BUILDTARGET` be better?

**Comment by yarons** [comment]
Yup, dpkg is way better indeed, how about BUILDTARGET? or we're skipping `buildx` for now?

**Comment by yarons** [comment]
I managed to replace it completely with the suggested dockerize by powerman, requires changing of methodolgy as this is a binary files that requires no compilation so it's possible to remove this build step and pull the binary directly.

**Comment by regisb** [comment]
@yarons @bradenmacdonald thanks again for your work. Based on your comments, I created a PR that downloads dockerize from the powerman fork. I decided not to make use of BUILDTARGET/BUILDPLATFORM/TARGETPLATFORM because these values are only available with buildx (AFAIU) and not with the generic `docker build` command. 

I attempted to download the powerman release binaries on amd64 and arm64 with various utilities to print the architecture. To test on arm64 I used `buildx`. The results:

- `uname -m`: "x86_64" / "aarch64" (same with `uname -i` and `uname -p`)
- `dpkg --print-architecture`: "amd64" / "arm64"

No command gives us the right "x86_64" / "arm64" combination that we need to make an easy download from the powerman releases, so I had to use an ugly if/else statement.

Please let me know your thoughts: #608 

Note that if this PR works for you we will have to make a similar change to the tutor-forum plugin which also makes use of dockerize: https://github.com/overhangio/tutor-forum/blob/a96cb900439ecd219ba8d1fdfca8b3147ad57a4c/tutorforum/templates/forum/build/forum/Dockerfile#L10

**Comment by yarons** [comment]
I will send you some well formed bash5 inline replacement, should be something like:
dpkg --architecture | sed 's@aarch@arm@'

I'll work on it and send it when I'll get to my computer.

**Comment by yarons** [comment]
Well, it's interchangable:

`dpkg --print-architecture | sed 's@amd@x86_@'`
`uname -i | sed 's@aarch@arm@'`

These command work on both platforms.

**Comment by regisb** [comment]
`sed` is much better than `if ... else`. I'll make the change in the PR.
