### ISSUE TITLE
`tutor local launch` should run to completion on ARM64 (M1/M2) Macs

### ISSUE THREAD

**Issue by feoh** [overhangio/tutor#821]
**Is your feature request related to a problem? Please describe.**

In [the official docs](https://docs.tutor.overhang.io/tutorials/arm64.html) we ask ARM64 users to trigger a build from source of the docker images required to run Tutor, in addition to manually changing the database configuration from mysql to mariadb.

This process is time consuming and a barrier to adoption for new OpenEdX users and developers running ARM64 macs.

**Describe the solution you'd like**

I want to have ARM64 docker images available from the official depots such that ARM64 users can run `tutor local launch` and have the entire end to end process be as flawless as it is curreently for users of Intel architecture machines.

**Describe alternatives you've considered**

**Additional context**

In Slack Régis mentioned [this plugin](https://github.com/open-craft/tutor-contrib-arm64/) which might help simplify this process. I'm not averse to that provided it is officially supported and stays up to date with the rest of tutor, and that offocial getting started docs were modified to reflect its proper use. I tried this plugin but was unable to get it to have any effect.

**Comment by feoh** [comment]
Filed an [issue](https://github.com/open-craft/tutor-contrib-arm64/issues/2) against the tutor-contrib-arm64 plugin with my experience trying to follow the instructions to run tutor with it.

**Comment by feoh** [comment]
FWIW I was able to get the plugin working locally if I built it myself and installed it from the local file.

I suspect all that's needed for a win here is some added polish and an update of the offocial docs. Happy to help any way I can there.

**Comment by chasemcdo** [comment]
Since this issue was _recently_ opened and is related to the work I have been doing. A fix I have found for ARM64 on Apple Silicone is to emulate the docker containers using Rosetta 2. This means adding a docker-compose overwrite file as follows:
```
# local/env/docker-compose.override.yml
services:
  mysql:
    platform: linux/amd64  
  
  lms:
    platform: linux/amd64  
  
  cms:
    platform: linux/amd64  

```

This allows `tutor local launch` to run and should be a pretty easy update to the default docker-compose files if reliance on emulation is an acceptable approach for Apple Silicone compatibility.

**Comment by chasemcdo** [comment]
@bradenmacdonald you're definitely right that there is a performance hit when leaning on emulation. 
[This stack overflow post](https://stackoverflow.com/questions/73605175/why-cant-qemu-get-even-close-to-rosetta-2s-performance-when-translating-x86-to) touches on the implementation difference between Qemu and Rosetta 2, which implies Rosetta 2 shouldn't have as significant of a performance hit with most sources citing a ~20% performance hit.

Our team is composed of developers on x86 and ARM Macs, so we've opted for emulation that runs out of the box on both devices with the performance hit instead of having to make adjustments for one of the stations. (If I understand [this plugin](https://github.com/open-craft/tutor-contrib-arm64/) correctly, it pulls an Unofficial Openedx image built for ARM, which would not work natively on x86 and still require the MySQL replacement with Mariadb)

As feoh had mentioned the ideal scenario would be to have officially supported images for both ARM and x86 which would remove the need for this plugin, but still be dependent on the Mariadb replacement or MySQL emulation.

**Comment by bradenmacdonald** [comment]
@chasemcdo The plugin (which I wrote) actually uses MySQL 8, which I now recommend instead of MariaDB. I've been meaning to update the docs. You are right that the plugin is not designed to be used on _both_ x86 and ARM so if you have some requirement that your developers have the exact same set of plugins across different x86 and ARM machines then you may prefer emulation.

As for the images not being "officially supported" you are right, for now it's just me building the images but the thing about tutor is that building images is really easy, so if I ever stopped publishing useful images for the arm64 plugin, it would be trivial to switch to your own docker image repo and build+host the images yourself. So I don't think the unofficial nature confers much risk. It's just there to save you time by having prebuilt images out of the box instead of spending a few minutes to build them yourself (which again, is quite easy to do).

**Comment by bradenmacdonald** [comment]
I have opened a PR to update the Tutor docs related to ARM64: https://github.com/overhangio/tutor/pull/826

**Comment by regisb** [comment]
This will be resolved in Palm: I have setup a multi-arch CI that includes both linux/amd64 and linux/arm64 targets. This was surprisingly easy. The only issue is that it's freaking expensive... I need to run a $100/month arm64 server on AWS just to get these images to build... Someone please launch a startup to solve this issue!

**Comment by bradenmacdonald** [comment]
Thank you @regisb, that's great!

Re costs, did you consider building the ARM images from a regular amd64 host, using qemu, as [I am doing for the plugin](https://github.com/open-craft/tutor-contrib-arm64/blob/bc941a7002e7a2e497591582a1b553402e25234e/.github/workflows/build.yaml#L19-L44)? It's damn slow especially on GitHub's CI, but it doesn't require an expensive ARM instance. In fact, on GitHub CI it was free.

**Comment by regisb** [comment]
This is now solved in Palm.
