### ISSUE TITLE
Is the "RUN_CADDY" function returning?

### ISSUE THREAD

**Issue by CodeWithEmad** [overhangio/tutor#849]
In many Kubernetes setups, an ingress controller can replace the need for Caddy.
In older versions of Tutor, there was a "RUN_CADDY" option in the configuration, which has now been replaced with "ENABLE_WEB_PROXY" (not sure exactly).
I was wondering if it would be feasible to have an "ingress.yaml" file when the "RUN_CADDY" parameter is disabled, and consequently, remove Caddy from the stack?

**Comment by regisb** [comment]
It's funny how so many people want to get rid of Caddy :) There is a common misunderstanding that:

1. Caddy is acting as an Ingress and it's all it does.
2. In order to use a different Ingress, Caddy should be disabled entirely.

Both of these assumptions are _wrong_.

Sure Caddy acts as an Ingress by default on Kubernetes. But it also dispatches requests to the different services, sets the right headers, max upload size, etc. Replicating this configuration precisely is a frequent source of errors for people who want replace Caddy (99% of the time people want to replace Caddy for bad reasons).

Moreover, the Caddy Ingress can be disabled very easily by setting `ENABLE_WEB_PROXY=false`. This setting value preserves the Caddy container but removes its use as an Ingress. (As a consequence it also disables SSL termination.)

Thus, users who want to use a different Ingress should set `ENABLE_WEB_PROXY=false`, perform SSL termination and redirect all traffic to the Caddy container, which will then be in charge of redirecting traffic to the LMS, CMS, MFE, etc. This is much simpler than trying to replicate the Caddy configuration in the Ingress.

In the very worst case, if you really, _really_, _**really**_ want to bypass the Caddy container, what you can do is to keep it running, but run your own Ingress and redirect requests to the service containers. Caddy will just sit there and do nothing.

cc @lpm0073 who might also be interested in this answer ;)

(For debatable questions like this, I suggest you open a forum topic instead of a GitHub issue.)

**Comment by regisb** [comment]
I'll close this now @CodeWithEmad. Feel free to re-open if you think I did not address your question.

**Comment by CodeWithEmad** [comment]
sorry for the late response @regisb.
I broke my leg, really bad, and couldn't work for the last few days.
we'll discuss this later.

**Comment by regisb** [comment]
Oh crap! Rest well. Feel free to come back to this whenever you want.
